services:
  frontend:
    build:
      context: .
      target: dev
    image: elineas-auth-frontend
    container_name: elineas-auth-frontend
    restart: unless-stopped
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      NODE_ENV: development
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      - elineas-auth

networks:
  elineas-auth:
    name: elineas-auth_default
    external: true
