/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerifyEmailRouteImport } from './routes/verify-email'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthedUserRolesRouteImport } from './routes/_authed/user-roles'
import { Route as AuthedSessionsRouteImport } from './routes/_authed/sessions'
import { Route as AuthedProfileRouteImport } from './routes/_authed/profile'
import { Route as AuthedDocsRouteImport } from './routes/_authed/docs'
import { Route as AuthedDashboardRouteImport } from './routes/_authed/dashboard'
import { Route as AuthedSystemsIndexRouteImport } from './routes/_authed/systems.index'
import { Route as AuthedRolesIndexRouteImport } from './routes/_authed/roles.index'
import { Route as AuthedEmployeesIndexRouteImport } from './routes/_authed/employees.index'
import { Route as AuthedSystemsNewRouteImport } from './routes/_authed/systems.new'
import { Route as AuthedRolesNewRouteImport } from './routes/_authed/roles.new'
import { Route as AuthedEmployeesNewRouteImport } from './routes/_authed/employees.new'
import { Route as AuthedSystemsSystemIdIndexRouteImport } from './routes/_authed/systems.$systemId.index'
import { Route as AuthedEmployeesEmployeeIdIndexRouteImport } from './routes/_authed/employees.$employeeId.index'
import { Route as AuthedSystemsSystemIdEditRouteImport } from './routes/_authed/systems.$systemId.edit'
import { Route as AuthedRolesRoleIdEditRouteImport } from './routes/_authed/roles.$roleId.edit'
import { Route as AuthedEmployeesEmployeeIdEditRouteImport } from './routes/_authed/employees.$employeeId.edit'

const VerifyEmailRoute = VerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedUserRolesRoute = AuthedUserRolesRouteImport.update({
  id: '/user-roles',
  path: '/user-roles',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedSessionsRoute = AuthedSessionsRouteImport.update({
  id: '/sessions',
  path: '/sessions',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedProfileRoute = AuthedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedDocsRoute = AuthedDocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedDashboardRoute = AuthedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedSystemsIndexRoute = AuthedSystemsIndexRouteImport.update({
  id: '/systems/',
  path: '/systems/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedRolesIndexRoute = AuthedRolesIndexRouteImport.update({
  id: '/roles/',
  path: '/roles/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedEmployeesIndexRoute = AuthedEmployeesIndexRouteImport.update({
  id: '/employees/',
  path: '/employees/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedSystemsNewRoute = AuthedSystemsNewRouteImport.update({
  id: '/systems/new',
  path: '/systems/new',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedRolesNewRoute = AuthedRolesNewRouteImport.update({
  id: '/roles/new',
  path: '/roles/new',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedEmployeesNewRoute = AuthedEmployeesNewRouteImport.update({
  id: '/employees/new',
  path: '/employees/new',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedSystemsSystemIdIndexRoute =
  AuthedSystemsSystemIdIndexRouteImport.update({
    id: '/systems/$systemId/',
    path: '/systems/$systemId/',
    getParentRoute: () => AuthedRoute,
  } as any)
const AuthedEmployeesEmployeeIdIndexRoute =
  AuthedEmployeesEmployeeIdIndexRouteImport.update({
    id: '/employees/$employeeId/',
    path: '/employees/$employeeId/',
    getParentRoute: () => AuthedRoute,
  } as any)
const AuthedSystemsSystemIdEditRoute =
  AuthedSystemsSystemIdEditRouteImport.update({
    id: '/systems/$systemId/edit',
    path: '/systems/$systemId/edit',
    getParentRoute: () => AuthedRoute,
  } as any)
const AuthedRolesRoleIdEditRoute = AuthedRolesRoleIdEditRouteImport.update({
  id: '/roles/$roleId/edit',
  path: '/roles/$roleId/edit',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedEmployeesEmployeeIdEditRoute =
  AuthedEmployeesEmployeeIdEditRouteImport.update({
    id: '/employees/$employeeId/edit',
    path: '/employees/$employeeId/edit',
    getParentRoute: () => AuthedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/verify-email': typeof VerifyEmailRoute
  '/dashboard': typeof AuthedDashboardRoute
  '/docs': typeof AuthedDocsRoute
  '/profile': typeof AuthedProfileRoute
  '/sessions': typeof AuthedSessionsRoute
  '/user-roles': typeof AuthedUserRolesRoute
  '/employees/new': typeof AuthedEmployeesNewRoute
  '/roles/new': typeof AuthedRolesNewRoute
  '/systems/new': typeof AuthedSystemsNewRoute
  '/employees/': typeof AuthedEmployeesIndexRoute
  '/roles/': typeof AuthedRolesIndexRoute
  '/systems/': typeof AuthedSystemsIndexRoute
  '/employees/$employeeId/edit': typeof AuthedEmployeesEmployeeIdEditRoute
  '/roles/$roleId/edit': typeof AuthedRolesRoleIdEditRoute
  '/systems/$systemId/edit': typeof AuthedSystemsSystemIdEditRoute
  '/employees/$employeeId/': typeof AuthedEmployeesEmployeeIdIndexRoute
  '/systems/$systemId/': typeof AuthedSystemsSystemIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/verify-email': typeof VerifyEmailRoute
  '/dashboard': typeof AuthedDashboardRoute
  '/docs': typeof AuthedDocsRoute
  '/profile': typeof AuthedProfileRoute
  '/sessions': typeof AuthedSessionsRoute
  '/user-roles': typeof AuthedUserRolesRoute
  '/employees/new': typeof AuthedEmployeesNewRoute
  '/roles/new': typeof AuthedRolesNewRoute
  '/systems/new': typeof AuthedSystemsNewRoute
  '/employees': typeof AuthedEmployeesIndexRoute
  '/roles': typeof AuthedRolesIndexRoute
  '/systems': typeof AuthedSystemsIndexRoute
  '/employees/$employeeId/edit': typeof AuthedEmployeesEmployeeIdEditRoute
  '/roles/$roleId/edit': typeof AuthedRolesRoleIdEditRoute
  '/systems/$systemId/edit': typeof AuthedSystemsSystemIdEditRoute
  '/employees/$employeeId': typeof AuthedEmployeesEmployeeIdIndexRoute
  '/systems/$systemId': typeof AuthedSystemsSystemIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authed': typeof AuthedRouteWithChildren
  '/verify-email': typeof VerifyEmailRoute
  '/_authed/dashboard': typeof AuthedDashboardRoute
  '/_authed/docs': typeof AuthedDocsRoute
  '/_authed/profile': typeof AuthedProfileRoute
  '/_authed/sessions': typeof AuthedSessionsRoute
  '/_authed/user-roles': typeof AuthedUserRolesRoute
  '/_authed/employees/new': typeof AuthedEmployeesNewRoute
  '/_authed/roles/new': typeof AuthedRolesNewRoute
  '/_authed/systems/new': typeof AuthedSystemsNewRoute
  '/_authed/employees/': typeof AuthedEmployeesIndexRoute
  '/_authed/roles/': typeof AuthedRolesIndexRoute
  '/_authed/systems/': typeof AuthedSystemsIndexRoute
  '/_authed/employees/$employeeId/edit': typeof AuthedEmployeesEmployeeIdEditRoute
  '/_authed/roles/$roleId/edit': typeof AuthedRolesRoleIdEditRoute
  '/_authed/systems/$systemId/edit': typeof AuthedSystemsSystemIdEditRoute
  '/_authed/employees/$employeeId/': typeof AuthedEmployeesEmployeeIdIndexRoute
  '/_authed/systems/$systemId/': typeof AuthedSystemsSystemIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/verify-email'
    | '/dashboard'
    | '/docs'
    | '/profile'
    | '/sessions'
    | '/user-roles'
    | '/employees/new'
    | '/roles/new'
    | '/systems/new'
    | '/employees/'
    | '/roles/'
    | '/systems/'
    | '/employees/$employeeId/edit'
    | '/roles/$roleId/edit'
    | '/systems/$systemId/edit'
    | '/employees/$employeeId/'
    | '/systems/$systemId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/verify-email'
    | '/dashboard'
    | '/docs'
    | '/profile'
    | '/sessions'
    | '/user-roles'
    | '/employees/new'
    | '/roles/new'
    | '/systems/new'
    | '/employees'
    | '/roles'
    | '/systems'
    | '/employees/$employeeId/edit'
    | '/roles/$roleId/edit'
    | '/systems/$systemId/edit'
    | '/employees/$employeeId'
    | '/systems/$systemId'
  id:
    | '__root__'
    | '/'
    | '/_authed'
    | '/verify-email'
    | '/_authed/dashboard'
    | '/_authed/docs'
    | '/_authed/profile'
    | '/_authed/sessions'
    | '/_authed/user-roles'
    | '/_authed/employees/new'
    | '/_authed/roles/new'
    | '/_authed/systems/new'
    | '/_authed/employees/'
    | '/_authed/roles/'
    | '/_authed/systems/'
    | '/_authed/employees/$employeeId/edit'
    | '/_authed/roles/$roleId/edit'
    | '/_authed/systems/$systemId/edit'
    | '/_authed/employees/$employeeId/'
    | '/_authed/systems/$systemId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthedRoute: typeof AuthedRouteWithChildren
  VerifyEmailRoute: typeof VerifyEmailRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verify-email': {
      id: '/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof VerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/user-roles': {
      id: '/_authed/user-roles'
      path: '/user-roles'
      fullPath: '/user-roles'
      preLoaderRoute: typeof AuthedUserRolesRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/sessions': {
      id: '/_authed/sessions'
      path: '/sessions'
      fullPath: '/sessions'
      preLoaderRoute: typeof AuthedSessionsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/profile': {
      id: '/_authed/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthedProfileRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/docs': {
      id: '/_authed/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof AuthedDocsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/dashboard': {
      id: '/_authed/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthedDashboardRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/systems/': {
      id: '/_authed/systems/'
      path: '/systems'
      fullPath: '/systems/'
      preLoaderRoute: typeof AuthedSystemsIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/roles/': {
      id: '/_authed/roles/'
      path: '/roles'
      fullPath: '/roles/'
      preLoaderRoute: typeof AuthedRolesIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/employees/': {
      id: '/_authed/employees/'
      path: '/employees'
      fullPath: '/employees/'
      preLoaderRoute: typeof AuthedEmployeesIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/systems/new': {
      id: '/_authed/systems/new'
      path: '/systems/new'
      fullPath: '/systems/new'
      preLoaderRoute: typeof AuthedSystemsNewRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/roles/new': {
      id: '/_authed/roles/new'
      path: '/roles/new'
      fullPath: '/roles/new'
      preLoaderRoute: typeof AuthedRolesNewRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/employees/new': {
      id: '/_authed/employees/new'
      path: '/employees/new'
      fullPath: '/employees/new'
      preLoaderRoute: typeof AuthedEmployeesNewRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/systems/$systemId/': {
      id: '/_authed/systems/$systemId/'
      path: '/systems/$systemId'
      fullPath: '/systems/$systemId/'
      preLoaderRoute: typeof AuthedSystemsSystemIdIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/employees/$employeeId/': {
      id: '/_authed/employees/$employeeId/'
      path: '/employees/$employeeId'
      fullPath: '/employees/$employeeId/'
      preLoaderRoute: typeof AuthedEmployeesEmployeeIdIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/systems/$systemId/edit': {
      id: '/_authed/systems/$systemId/edit'
      path: '/systems/$systemId/edit'
      fullPath: '/systems/$systemId/edit'
      preLoaderRoute: typeof AuthedSystemsSystemIdEditRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/roles/$roleId/edit': {
      id: '/_authed/roles/$roleId/edit'
      path: '/roles/$roleId/edit'
      fullPath: '/roles/$roleId/edit'
      preLoaderRoute: typeof AuthedRolesRoleIdEditRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/employees/$employeeId/edit': {
      id: '/_authed/employees/$employeeId/edit'
      path: '/employees/$employeeId/edit'
      fullPath: '/employees/$employeeId/edit'
      preLoaderRoute: typeof AuthedEmployeesEmployeeIdEditRouteImport
      parentRoute: typeof AuthedRoute
    }
  }
}

interface AuthedRouteChildren {
  AuthedDashboardRoute: typeof AuthedDashboardRoute
  AuthedDocsRoute: typeof AuthedDocsRoute
  AuthedProfileRoute: typeof AuthedProfileRoute
  AuthedSessionsRoute: typeof AuthedSessionsRoute
  AuthedUserRolesRoute: typeof AuthedUserRolesRoute
  AuthedEmployeesNewRoute: typeof AuthedEmployeesNewRoute
  AuthedRolesNewRoute: typeof AuthedRolesNewRoute
  AuthedSystemsNewRoute: typeof AuthedSystemsNewRoute
  AuthedEmployeesIndexRoute: typeof AuthedEmployeesIndexRoute
  AuthedRolesIndexRoute: typeof AuthedRolesIndexRoute
  AuthedSystemsIndexRoute: typeof AuthedSystemsIndexRoute
  AuthedEmployeesEmployeeIdEditRoute: typeof AuthedEmployeesEmployeeIdEditRoute
  AuthedRolesRoleIdEditRoute: typeof AuthedRolesRoleIdEditRoute
  AuthedSystemsSystemIdEditRoute: typeof AuthedSystemsSystemIdEditRoute
  AuthedEmployeesEmployeeIdIndexRoute: typeof AuthedEmployeesEmployeeIdIndexRoute
  AuthedSystemsSystemIdIndexRoute: typeof AuthedSystemsSystemIdIndexRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedDashboardRoute: AuthedDashboardRoute,
  AuthedDocsRoute: AuthedDocsRoute,
  AuthedProfileRoute: AuthedProfileRoute,
  AuthedSessionsRoute: AuthedSessionsRoute,
  AuthedUserRolesRoute: AuthedUserRolesRoute,
  AuthedEmployeesNewRoute: AuthedEmployeesNewRoute,
  AuthedRolesNewRoute: AuthedRolesNewRoute,
  AuthedSystemsNewRoute: AuthedSystemsNewRoute,
  AuthedEmployeesIndexRoute: AuthedEmployeesIndexRoute,
  AuthedRolesIndexRoute: AuthedRolesIndexRoute,
  AuthedSystemsIndexRoute: AuthedSystemsIndexRoute,
  AuthedEmployeesEmployeeIdEditRoute: AuthedEmployeesEmployeeIdEditRoute,
  AuthedRolesRoleIdEditRoute: AuthedRolesRoleIdEditRoute,
  AuthedSystemsSystemIdEditRoute: AuthedSystemsSystemIdEditRoute,
  AuthedEmployeesEmployeeIdIndexRoute: AuthedEmployeesEmployeeIdIndexRoute,
  AuthedSystemsSystemIdIndexRoute: AuthedSystemsSystemIdIndexRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthedRoute: AuthedRouteWithChildren,
  VerifyEmailRoute: VerifyEmailRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
