/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthedUserRolesRouteImport } from './routes/_authed/user-roles'
import { Route as AuthedSessionsRouteImport } from './routes/_authed/sessions'
import { Route as AuthedRolesRouteImport } from './routes/_authed/roles'
import { Route as AuthedProfileRouteImport } from './routes/_authed/profile'
import { Route as AuthedDashboardRouteImport } from './routes/_authed/dashboard'
import { Route as AuthedSystemsIndexRouteImport } from './routes/_authed/systems.index'
import { Route as AuthedEmployeesIndexRouteImport } from './routes/_authed/employees.index'
import { Route as AuthedSystemsNewRouteImport } from './routes/_authed/systems.new'
import { Route as AuthedEmployeesNewRouteImport } from './routes/_authed/employees.new'
import { Route as AuthedSystemsSystemIdIndexRouteImport } from './routes/_authed/systems.$systemId.index'
import { Route as AuthedEmployeesEmployeeIdIndexRouteImport } from './routes/_authed/employees.$employeeId.index'
import { Route as AuthedSystemsSystemIdEditRouteImport } from './routes/_authed/systems.$systemId.edit'
import { Route as AuthedEmployeesEmployeeIdEditRouteImport } from './routes/_authed/employees.$employeeId.edit'

const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedUserRolesRoute = AuthedUserRolesRouteImport.update({
  id: '/user-roles',
  path: '/user-roles',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedSessionsRoute = AuthedSessionsRouteImport.update({
  id: '/sessions',
  path: '/sessions',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedRolesRoute = AuthedRolesRouteImport.update({
  id: '/roles',
  path: '/roles',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedProfileRoute = AuthedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedDashboardRoute = AuthedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedSystemsIndexRoute = AuthedSystemsIndexRouteImport.update({
  id: '/systems/',
  path: '/systems/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedEmployeesIndexRoute = AuthedEmployeesIndexRouteImport.update({
  id: '/employees/',
  path: '/employees/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedSystemsNewRoute = AuthedSystemsNewRouteImport.update({
  id: '/systems/new',
  path: '/systems/new',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedEmployeesNewRoute = AuthedEmployeesNewRouteImport.update({
  id: '/employees/new',
  path: '/employees/new',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedSystemsSystemIdIndexRoute =
  AuthedSystemsSystemIdIndexRouteImport.update({
    id: '/systems/$systemId/',
    path: '/systems/$systemId/',
    getParentRoute: () => AuthedRoute,
  } as any)
const AuthedEmployeesEmployeeIdIndexRoute =
  AuthedEmployeesEmployeeIdIndexRouteImport.update({
    id: '/employees/$employeeId/',
    path: '/employees/$employeeId/',
    getParentRoute: () => AuthedRoute,
  } as any)
const AuthedSystemsSystemIdEditRoute =
  AuthedSystemsSystemIdEditRouteImport.update({
    id: '/systems/$systemId/edit',
    path: '/systems/$systemId/edit',
    getParentRoute: () => AuthedRoute,
  } as any)
const AuthedEmployeesEmployeeIdEditRoute =
  AuthedEmployeesEmployeeIdEditRouteImport.update({
    id: '/employees/$employeeId/edit',
    path: '/employees/$employeeId/edit',
    getParentRoute: () => AuthedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof AuthedDashboardRoute
  '/profile': typeof AuthedProfileRoute
  '/roles': typeof AuthedRolesRoute
  '/sessions': typeof AuthedSessionsRoute
  '/user-roles': typeof AuthedUserRolesRoute
  '/employees/new': typeof AuthedEmployeesNewRoute
  '/systems/new': typeof AuthedSystemsNewRoute
  '/employees/': typeof AuthedEmployeesIndexRoute
  '/systems/': typeof AuthedSystemsIndexRoute
  '/employees/$employeeId/edit': typeof AuthedEmployeesEmployeeIdEditRoute
  '/systems/$systemId/edit': typeof AuthedSystemsSystemIdEditRoute
  '/employees/$employeeId/': typeof AuthedEmployeesEmployeeIdIndexRoute
  '/systems/$systemId/': typeof AuthedSystemsSystemIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof AuthedDashboardRoute
  '/profile': typeof AuthedProfileRoute
  '/roles': typeof AuthedRolesRoute
  '/sessions': typeof AuthedSessionsRoute
  '/user-roles': typeof AuthedUserRolesRoute
  '/employees/new': typeof AuthedEmployeesNewRoute
  '/systems/new': typeof AuthedSystemsNewRoute
  '/employees': typeof AuthedEmployeesIndexRoute
  '/systems': typeof AuthedSystemsIndexRoute
  '/employees/$employeeId/edit': typeof AuthedEmployeesEmployeeIdEditRoute
  '/systems/$systemId/edit': typeof AuthedSystemsSystemIdEditRoute
  '/employees/$employeeId': typeof AuthedEmployeesEmployeeIdIndexRoute
  '/systems/$systemId': typeof AuthedSystemsSystemIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authed': typeof AuthedRouteWithChildren
  '/_authed/dashboard': typeof AuthedDashboardRoute
  '/_authed/profile': typeof AuthedProfileRoute
  '/_authed/roles': typeof AuthedRolesRoute
  '/_authed/sessions': typeof AuthedSessionsRoute
  '/_authed/user-roles': typeof AuthedUserRolesRoute
  '/_authed/employees/new': typeof AuthedEmployeesNewRoute
  '/_authed/systems/new': typeof AuthedSystemsNewRoute
  '/_authed/employees/': typeof AuthedEmployeesIndexRoute
  '/_authed/systems/': typeof AuthedSystemsIndexRoute
  '/_authed/employees/$employeeId/edit': typeof AuthedEmployeesEmployeeIdEditRoute
  '/_authed/systems/$systemId/edit': typeof AuthedSystemsSystemIdEditRoute
  '/_authed/employees/$employeeId/': typeof AuthedEmployeesEmployeeIdIndexRoute
  '/_authed/systems/$systemId/': typeof AuthedSystemsSystemIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/profile'
    | '/roles'
    | '/sessions'
    | '/user-roles'
    | '/employees/new'
    | '/systems/new'
    | '/employees/'
    | '/systems/'
    | '/employees/$employeeId/edit'
    | '/systems/$systemId/edit'
    | '/employees/$employeeId/'
    | '/systems/$systemId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/profile'
    | '/roles'
    | '/sessions'
    | '/user-roles'
    | '/employees/new'
    | '/systems/new'
    | '/employees'
    | '/systems'
    | '/employees/$employeeId/edit'
    | '/systems/$systemId/edit'
    | '/employees/$employeeId'
    | '/systems/$systemId'
  id:
    | '__root__'
    | '/'
    | '/_authed'
    | '/_authed/dashboard'
    | '/_authed/profile'
    | '/_authed/roles'
    | '/_authed/sessions'
    | '/_authed/user-roles'
    | '/_authed/employees/new'
    | '/_authed/systems/new'
    | '/_authed/employees/'
    | '/_authed/systems/'
    | '/_authed/employees/$employeeId/edit'
    | '/_authed/systems/$systemId/edit'
    | '/_authed/employees/$employeeId/'
    | '/_authed/systems/$systemId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthedRoute: typeof AuthedRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/user-roles': {
      id: '/_authed/user-roles'
      path: '/user-roles'
      fullPath: '/user-roles'
      preLoaderRoute: typeof AuthedUserRolesRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/sessions': {
      id: '/_authed/sessions'
      path: '/sessions'
      fullPath: '/sessions'
      preLoaderRoute: typeof AuthedSessionsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/roles': {
      id: '/_authed/roles'
      path: '/roles'
      fullPath: '/roles'
      preLoaderRoute: typeof AuthedRolesRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/profile': {
      id: '/_authed/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthedProfileRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/dashboard': {
      id: '/_authed/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthedDashboardRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/systems/': {
      id: '/_authed/systems/'
      path: '/systems'
      fullPath: '/systems/'
      preLoaderRoute: typeof AuthedSystemsIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/employees/': {
      id: '/_authed/employees/'
      path: '/employees'
      fullPath: '/employees/'
      preLoaderRoute: typeof AuthedEmployeesIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/systems/new': {
      id: '/_authed/systems/new'
      path: '/systems/new'
      fullPath: '/systems/new'
      preLoaderRoute: typeof AuthedSystemsNewRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/employees/new': {
      id: '/_authed/employees/new'
      path: '/employees/new'
      fullPath: '/employees/new'
      preLoaderRoute: typeof AuthedEmployeesNewRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/systems/$systemId/': {
      id: '/_authed/systems/$systemId/'
      path: '/systems/$systemId'
      fullPath: '/systems/$systemId/'
      preLoaderRoute: typeof AuthedSystemsSystemIdIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/employees/$employeeId/': {
      id: '/_authed/employees/$employeeId/'
      path: '/employees/$employeeId'
      fullPath: '/employees/$employeeId/'
      preLoaderRoute: typeof AuthedEmployeesEmployeeIdIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/systems/$systemId/edit': {
      id: '/_authed/systems/$systemId/edit'
      path: '/systems/$systemId/edit'
      fullPath: '/systems/$systemId/edit'
      preLoaderRoute: typeof AuthedSystemsSystemIdEditRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/employees/$employeeId/edit': {
      id: '/_authed/employees/$employeeId/edit'
      path: '/employees/$employeeId/edit'
      fullPath: '/employees/$employeeId/edit'
      preLoaderRoute: typeof AuthedEmployeesEmployeeIdEditRouteImport
      parentRoute: typeof AuthedRoute
    }
  }
}

interface AuthedRouteChildren {
  AuthedDashboardRoute: typeof AuthedDashboardRoute
  AuthedProfileRoute: typeof AuthedProfileRoute
  AuthedRolesRoute: typeof AuthedRolesRoute
  AuthedSessionsRoute: typeof AuthedSessionsRoute
  AuthedUserRolesRoute: typeof AuthedUserRolesRoute
  AuthedEmployeesNewRoute: typeof AuthedEmployeesNewRoute
  AuthedSystemsNewRoute: typeof AuthedSystemsNewRoute
  AuthedEmployeesIndexRoute: typeof AuthedEmployeesIndexRoute
  AuthedSystemsIndexRoute: typeof AuthedSystemsIndexRoute
  AuthedEmployeesEmployeeIdEditRoute: typeof AuthedEmployeesEmployeeIdEditRoute
  AuthedSystemsSystemIdEditRoute: typeof AuthedSystemsSystemIdEditRoute
  AuthedEmployeesEmployeeIdIndexRoute: typeof AuthedEmployeesEmployeeIdIndexRoute
  AuthedSystemsSystemIdIndexRoute: typeof AuthedSystemsSystemIdIndexRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedDashboardRoute: AuthedDashboardRoute,
  AuthedProfileRoute: AuthedProfileRoute,
  AuthedRolesRoute: AuthedRolesRoute,
  AuthedSessionsRoute: AuthedSessionsRoute,
  AuthedUserRolesRoute: AuthedUserRolesRoute,
  AuthedEmployeesNewRoute: AuthedEmployeesNewRoute,
  AuthedSystemsNewRoute: AuthedSystemsNewRoute,
  AuthedEmployeesIndexRoute: AuthedEmployeesIndexRoute,
  AuthedSystemsIndexRoute: AuthedSystemsIndexRoute,
  AuthedEmployeesEmployeeIdEditRoute: AuthedEmployeesEmployeeIdEditRoute,
  AuthedSystemsSystemIdEditRoute: AuthedSystemsSystemIdEditRoute,
  AuthedEmployeesEmployeeIdIndexRoute: AuthedEmployeesEmployeeIdIndexRoute,
  AuthedSystemsSystemIdIndexRoute: AuthedSystemsSystemIdIndexRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthedRoute: AuthedRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
